# Generated by Django 2.2.3 on 2019-11-08 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
