# Generated by Django 2.2.3 on 2019-11-08 14:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191108_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
